# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=255, unique=True)),
                ('common_name', models.CharField(blank=True, default='', max_length=255)),
                ('family', models.CharField(blank=True, default='', max_length=100)),
                ('genus', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('habitat', models.CharField(blank=True, choices=[('FOREST', 'Forest'), ('SAVANNA', 'Savanna'), ('MOUNTAIN', 'Mountain'), ('WETLAND', 'Wetland'), ('COASTAL', 'Coastal'), ('URBAN', 'Urban')], default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('image_credit', models.CharField(blank=True, default='', max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regions', models.ManyToManyField(blank=True, related_name='plants', to='geography.region')),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
        migrations.CreateModel(
            name='PlantLocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.community')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_names', to='plants.plant')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlantPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('LEAF', 'Leaf'), ('ROOT', 'Root'), ('BARK', 'Bark'), ('STEM', 'Stem'), ('FLOWER', 'Flower'), ('FRUIT', 'Fruit'), ('SEED', 'Seed'), ('TUBER', 'Tuber'), ('WHOLE', 'Whole Plant'), ('SAP', 'Sap/Latex'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='plants.plant')),
            ],
            options={
                'ordering': ['part_type'],
                'unique_together': {('plant', 'part_type')},
            },
        ),
    ]
