# Generated by Django 4.2.30 on 2026-09-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('IDENTIFICATION_READY', 'Identification Complete'), ('SUBMISSION_APPROVED', 'Submission Approved'), ('SUBMISSION_REJECTED', 'Submission Rejected'), ('SUBMISSION_REVISION', 'Revision Requested'), ('NEW_REVIEW', 'New Submission to Review'), ('APPOINTMENT_BOOKED', 'New Consultation Request'), ('APPOINTMENT_CONFIRMED', 'Consultation Confirmed'), ('APPOINTMENT_CANCELLED', 'Consultation Cancelled'), ('APPOINTMENT_COMPLETED', 'Consultation Completed'), ('APPOINTMENT_NO_SHOW', 'Consultation No-Show'), ('NEW_MESSAGE', 'New Message'), ('FEEDBACK_REPLY', 'Reply to your feedback'), ('SYSTEM', 'System Notification')], max_length=30),
        ),
    ]
