# Generated by Django 4.2.30 on 2026-09-23 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', help_text='What the patient wants to discuss.')),
                ('expert_notes', models.TextField(blank=True, default='', help_text='Private notes the consultant keeps on this consultation.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending confirmation'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='PENDING', max_length=12)),
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_expert', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='consultations.appointment')),
            ],
            options={
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('TEXT', 'Message'), ('JOIN', 'Entered the room'), ('LEAVE', 'Left the room'), ('OFFER', 'WebRTC offer'), ('ANSWER', 'WebRTC answer'), ('ICE', 'WebRTC ICE candidate')], default='TEXT', max_length=8)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('note', models.CharField(blank=True, default='', help_text='Optional line patients see next to this window, e.g. "Follow-ups only".', max_length=255)),
                ('is_closed', models.BooleanField(default=False, help_text='Hidden from patients. Does not cancel an existing booking.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='The diary window this booking claims.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='consultations.availabilityslot'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='slot_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['expert', 'status'], name='consultatio_expert__c2773c_idx'),
        ),
    ]
