# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('plants', '0001_initial'),
        ('symptoms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('DECOCTION', 'Decoction (Boiling)'), ('INFUSION', 'Infusion (Steeping)'), ('POULTICE', 'Poultice'), ('POWDER', 'Powder'), ('JUICE', 'Fresh Juice/Extract'), ('OINTMENT', 'Ointment/Salve'), ('TINCTURE', 'Tincture'), ('SMOKE', 'Smoking/Inhalation'), ('BATH', 'Medicinal Bath'), ('RAW', 'Raw Consumption'), ('OTHER', 'Other')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], default='DRAFT', max_length=20)),
                ('proposed_scientific_name', models.CharField(blank=True, default='', help_text='If plant not in database', max_length=255)),
                ('proposed_common_name', models.CharField(blank=True, default='', max_length=255)),
                ('local_name', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('proposed_symptom_name', models.CharField(blank=True, default='', help_text='If symptom not in database', max_length=255)),
                ('plant_part', models.CharField(blank=True, default='', max_length=50)),
                ('preparation_method', models.CharField(blank=True, default='', max_length=100)),
                ('traditional_use_description', models.TextField(help_text='Detailed description of the traditional use')),
                ('cultural_context', models.TextField(blank=True, default='')),
                ('community_name', models.CharField(blank=True, default='', help_text='If community not in database', max_length=255)),
                ('supporting_information', models.TextField(blank=True, default='', help_text='Sources, context, or supporting details')),
                ('review_comments', models.TextField(blank=True, default='')),
                ('review_reason', models.TextField(blank=True, default='', help_text='Reason for approval/rejection')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.community')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_submissions', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_submissions', to='plants.plant')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_reviews', to=settings.AUTH_USER_MODEL)),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_submissions', to='symptoms.symptom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TraditionalUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the traditional use')),
                ('cultural_context', models.TextField(blank=True, default='', help_text='Cultural or ceremonial context')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by expert reviewer')),
                ('source', models.CharField(blank=True, default='', help_text='Source of this knowledge (contributor, publication, etc.)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses', to='geography.community')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses_contributed', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_uses', to='plants.plant')),
                ('plant_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses', to='plants.plantpart')),
                ('preparation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses', to='knowledge.preparationmethod')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses', to='geography.region')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_uses', to='symptoms.symptom')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traditional_uses_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
