# Generated by Django 4.2.30 on 2026-08-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preparationmethod',
            options={'ordering': ['name']},
        ),
    ]
