# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('precautions', models.TextField(blank=True, default='', help_text='General precautions')),
                ('contraindications', models.TextField(blank=True, default='', help_text='Conditions where use is not recommended')),
                ('interactions', models.TextField(blank=True, default='', help_text='Known drug/herb interactions')),
                ('side_effects', models.TextField(blank=True, default='', help_text='Known side effects')),
                ('pregnancy_warning', models.BooleanField(default=False)),
                ('children_warning', models.BooleanField(default=False)),
                ('dosage_concerns', models.TextField(blank=True, default='')),
                ('preparation_concerns', models.TextField(blank=True, default='')),
                ('general_warning', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_records', to='plants.plant')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'safety information records',
                'ordering': ['-created_at'],
            },
        ),
    ]
