import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Edit3, Plus, Save, Search } from 'lucide-react';
import { articlesAPI, auditAPI, geographyAPI, knowledgeAPI, plantsAPI } from '../api/client';
import api from '../api/client';
const rows=r=>r?.data?.results||r?.data||[];
const Shell=({title,children,action})=><div className="space-y-6"><div className="rounded-2xl bg-gradient-to-br from-slate-900 to-emerald-900 p-6 text-white"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-200">HerbaCam administration</p><h2 className="mt-1 text-2xl font-bold">{title}</h2></div>{action}</div></div>{children}</div>;
const Loading=()=> <div className="h-40 animate-pulse rounded-2xl bg-stone-200"/>;
export function PlantsManagement(){const[d,setD]=useState(null),[f,setF]=useState(null);const load=()=>plantsAPI.adminList().then(r=>setD(rows(r))).catch(()=>setD([]));useEffect(load,[]);const save=e=>{e.preventDefault();(f.id?plantsAPI.adminUpdate(f.id,f):plantsAPI.adminCreate(f)).then(()=>{setF(null);load()})};return <Shell title="Plant library" action={<button onClick={()=>setF({is_published:true})} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-emerald-900"><Plus className="inline h-4"/> Add plant</button>}>{f&&<form onSubmit={save} className="grid gap-3 rounded-2xl bg-emerald-50 p-5 md:grid-cols-2"><input required className="rounded-xl border p-3" placeholder="Scientific name" value={f.scientific_name||''} onChange={e=>setF({...f,scientific_name:e.target.value})}/><input className="rounded-xl border p-3" placeholder="Common name" value={f.common_name||''} onChange={e=>setF({...f,common_name:e.target.value})}/><textarea className="rounded-xl border p-3 md:col-span-2" placeholder="Description" value={f.description||''} onChange={e=>setF({...f,description:e.target.value})}/><button className="rounded-xl bg-emerald-700 p-3 font-bold text-white">Save plant</button></form>}{!d?<Loading/>:<div className="grid gap-3">{d.map(x=><div key={x.id} className="flex justify-between rounded-xl border bg-white p-4"><span><b>{x.scientific_name}</b><small className="ml-2 text-stone-500">{x.common_name}</small></span><button onClick={()=>setF(x)}><Edit3 className="h-4 text-emerald-700"/></button></div>)}</div>}</Shell>}
export function KnowledgeManagement(){const[d,setD]=useState(null);useEffect(()=>knowledgeAPI.submissions().then(r=>setD(rows(r))).catch(()=>setD([])),[]);return <Shell title="Knowledge records">{!d?<Loading/>:<div className="grid gap-3">{d.map(x=><Link key={x.id} to={`/expert/reviews/${x.id}`} className="rounded-xl border bg-white p-4"><b>{x.plant_name||x.proposed_scientific_name||'Plant request'}</b><p className="text-sm text-stone-500">{x.contributor_name} · {x.status}</p></Link>)}</div>}</Shell>}
export function ArticlesManagement(){const[d,setD]=useState(null),[f,setF]=useState(null);const load=()=>articlesAPI.adminList().then(r=>setD(rows(r))).catch(()=>setD([]));useEffect(load,[]);const save=e=>{e.preventDefault();let x={...f,slug:(f.slug||f.title.toLowerCase().replace(/[^a-z0-9]+/g,'-')).replace(/(^-|-$)/g,'')};(f.id?articlesAPI.adminUpdate(f.id,x):articlesAPI.adminCreate(x)).then(()=>{setF(null);load()})};return <Shell title="Educational articles" action={<button onClick={()=>setF({is_published:false})} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-emerald-900"><Plus className="inline h-4"/> New article</button>}>{f&&<form onSubmit={save} className="grid gap-3 rounded-2xl bg-emerald-50 p-5"><input required className="rounded-xl border p-3" placeholder="Title" value={f.title||''} onChange={e=>setF({...f,title:e.target.value})}/><textarea required className="min-h-32 rounded-xl border p-3" placeholder="Content" value={f.content||''} onChange={e=>setF({...f,content:e.target.value})}/><label><input type="checkbox" checked={!!f.is_published} onChange={e=>setF({...f,is_published:e.target.checked})}/> Publish</label><button className="rounded-xl bg-emerald-700 p-3 font-bold text-white">Save article</button></form>}{!d?<Loading/>:<div className="grid gap-3">{d.map(x=><div className="flex justify-between rounded-xl border bg-white p-4" key={x.id}><span><b>{x.title}</b><small className="ml-2">{x.is_published?'Published':'Draft'}</small></span><button onClick={()=>setF(x)}><Edit3 className="h-4 text-emerald-700"/></button></div>)}</div>}</Shell>}
export function AuditLogs(){const[d,setD]=useState(null);useEffect(()=>auditAPI.list().then(r=>setD(rows(r))).catch(()=>setD([])),[]);return <Shell title="Audit logs">{!d?<Loading/>:<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-150 text-sm"><thead><tr><th className="p-3 text-left">User</th><th className="text-left">Action</th><th className="text-left">Object</th><th className="p-3 text-left">When</th></tr></thead><tbody>{d.map(x=><tr className="border-t" key={x.id}><td className="p-3">{x.username}</td><td>{x.action}</td><td>{x.target_type}</td><td className="p-3">{new Date(x.created_at).toLocaleString()}</td></tr>)}</tbody></table></div>}</Shell>}
export function SettingsPage(){const[f,setF]=useState({application:{name:'HerbaCam'},registration:{enabled:true},notifications:{email:true},content:{moderation:true},ai:{enabled:true}}),[m,setM]=useState('');useEffect(()=>api.get('/auth/settings/').then(r=>setF(x=>({...x,...r.data})).catch(()=>{})),[]);return <Shell title="System settings"><div className="grid gap-4 md:grid-cols-2">{Object.entries(f).map(([k,v])=><label className="rounded-xl border bg-white p-4" key={k}><b className="capitalize">{k}</b><textarea className="mt-2 min-h-28 w-full rounded-lg border p-2 text-xs" value={JSON.stringify(v,null,2)} onChange={e=>{try{setF({...f,[k]:JSON.parse(e.target.value)})}catch{}}}/></label>)}</div><button onClick={()=>api.put('/auth/settings/',f).then(()=>setM('Saved. Credentials are never exposed here.'))} className="rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white"><Save className="mr-2 inline h-4"/>Save configuration</button><p>{m}</p></Shell>}
export function GeographyManagement(){const[d,setD]=useState(null),[f,setF]=useState(null);const load=()=>geographyAPI.regions({detailed:1}).then(r=>setD(rows(r))).catch(()=>setD([]));useEffect(load,[]);return <Shell title="Geography" action={<button onClick={()=>setF({})} className="rounded-xl bg-white px-4 py-2 text-sm font-bold text-emerald-900">Add region</button>}>{f&&<form onSubmit={e=>{e.preventDefault();(f.id?geographyAPI.updateRegion(f.id,f):geographyAPI.createRegion(f)).then(()=>{setF(null);load()})}} className="grid gap-3 rounded-2xl bg-emerald-50 p-5"><input required className="rounded-xl border p-3" placeholder="Name" value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/><input required className="rounded-xl border p-3" placeholder="Code" value={f.code||''} onChange={e=>setF({...f,code:e.target.value})}/><button className="rounded-xl bg-emerald-700 p-3 font-bold text-white">Save region</button></form>}{!d?<Loading/>:<div className="grid gap-3 md:grid-cols-2">{d.map(x=><button key={x.id} onClick={()=>setF(x)} className="rounded-xl border bg-white p-4 text-left"><b>{x.name}</b><p className="text-sm text-stone-500">{x.code}</p></button>)}</div>}</Shell>}
