# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INSUFFICIENT', 'Insufficient'), ('PRELIMINARY', 'Preliminary'), ('MODERATE', 'Moderate'), ('STRONG', 'Strong')], max_length=20)),
                ('summary', models.TextField(help_text='Summary of the evidence')),
                ('source', models.CharField(help_text='Source/publication reference', max_length=500)),
                ('reference_url', models.URLField(blank=True, default='')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='plants.plant')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'evidence records',
                'ordering': ['-created_at'],
            },
        ),
    ]
