# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(blank=True, default='', max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('areas_of_knowledge', models.TextField(blank=True, default='', help_text='Areas of traditional medicine expertise')),
                ('traditional_training', models.TextField(blank=True, default='', help_text='How they learned traditional medicine')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by admin as legitimate practitioner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practitioner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
