# Generated by Django 4.2.30 on 2026-08-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practitioners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitionerprofile',
            options={'ordering': ['created_at']},
        ),
    ]
