# Generated by Django 5.2.17 on 2026-08-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(help_text='Risk score 0-100')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=20)),
                ('contributor_scarcity_score', models.FloatField(default=0)),
                ('knowledge_recency_score', models.FloatField(default=0)),
                ('geographic_concentration_score', models.FloatField(default=0)),
                ('documentation_scarcity_score', models.FloatField(default=0)),
                ('submission_decline_score', models.FloatField(default=0)),
                ('total_contributors', models.IntegerField(default=0)),
                ('total_traditional_uses', models.IntegerField(default=0)),
                ('days_since_last_contribution', models.IntegerField(default=0)),
                ('unique_regions_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='plants.plant')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='geography.region')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
    ]
