# Generated by Django 4.2.30 on 2026-09-23 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'Bug or defect'), ('SUGGESTION', 'Improvement idea'), ('CONTENT', 'Content or knowledge correction'), ('DATA', 'Missing plant or region data'), ('OTHER', 'Something else')], default='OTHER', max_length=12)),
                ('message', models.TextField(max_length=4000)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional 1-5 satisfaction rating.', null=True)),
                ('page', models.CharField(blank=True, default='', help_text='Path the user was on when they sent it.', max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_REVIEW', 'In review'), ('RESOLVED', 'Resolved')], default='NEW', max_length=12)),
                ('admin_response', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
